# Generated by Django 6.1.1 on 2026-09-20 07:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo_rastreo', models.CharField(max_length=100)),
                ('direccion_entrega', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='ventas.pedido')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='envios.transportista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField(blank=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='envios.envio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
